### ISSUE TITLE
Something Wrong after Merge?

### ISSUE THREAD

**Issue by wudijimao** [cxjwin/CoreTextDemo_cxjwin#1]
> > > > > > > > > > > > > > > FETCH_HEAD
> > > > > > > > > > > > > > > ## xxx
> > > > > > > > > > > > > > > 
> > > > > > > > > > > > > > > HEAD
> > > > > > > > > > > > > > > ## xxx

**Comment by cxjwin** [comment]
yes, I did't check it.
